# Generated by Django 5.1.7 on 2025-04-01 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tutorial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredRoles',
            fields=[
                ('required_roles_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('ELECTRICAL_ENGINEER', 'Electrical Engineer'), ('MECHANICAL_ENGINEER', 'Mechanical Engineer'), ('SOFTWARE_ENGINEER', 'Software Engineer'), ('CHEMICAL_ENGINEER', 'Chemical Engineer'), ('CIVIL_ENGINEER', 'Civil Engineer'), ('INDUSTRIAL_ENGINEER', 'Industrial Engineer'), ('ENGINEER', 'Engineer'), ('MATHEMATICIAN', 'Mathematician'), ('SCIENTIST', 'Scientist'), ('COLLABORATOR', 'Collaborator'), ('REVIEWER', 'Reviewer'), ('MENTOR', 'Mentor'), ('OBSERVER', 'Observer'), ('LEAD_AUTHOR', 'Lead Author'), ('CO_AUTHOR', 'Co-Author'), ('PAPER_REVIEWER', 'Paper Reviewer'), ('VIEWER', 'Viewer')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of people required for this role')),
                ('required_profession', models.CharField(blank=True, help_text='Optional: specific professional title required', max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Required-Roles',
                'verbose_name_plural': 'Required-Roles',
            },
        ),
    ]
