# Generated by Django 5.1.7 on 2025-04-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=9),
        ),
    ]
