# Generated by Django 5.1.7 on 2025-05-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_image'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requiredroles',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='requiredroles',
            unique_together={('content_type', 'object_id', 'role')},
        ),
        migrations.AddField(
            model_name='requiredroles',
            name='details',
            field=models.TextField(blank=True, help_text="Describe skills, academic title, tools, etc which          applicant's would need to have to apply for the certain roles."),
        ),
        migrations.AlterField(
            model_name='requiredroles',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='requiredroles',
            name='required_profession',
        ),
    ]
