# Generated by Django 5.1.4 on 2025-05-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='role_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='RequiredRoles',
        ),
    ]
