# Generated by Django 5.1.7 on 2025-05-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_paper_role_details_project_role_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='accepting_applications',
            field=models.BooleanField(default=True, help_text='Can people apply right now?'),
        ),
        migrations.AddField(
            model_name='project',
            name='accepting_applications',
            field=models.BooleanField(default=True, help_text='Can people apply right now?'),
        ),
    ]
