# Generated by Django 5.1.7 on 2025-06-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
