# Generated by Django 5.1.7 on 2025-06-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_paper_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaper',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
