# Generated by Django 5.1.7 on 2025-06-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_userpaper_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(help_text="Role I'm inviting the receiver to fill in", max_length=50, null=True),
        ),
    ]
